### PR TITLE
Feature/update configuration

### PR DESCRIPTION
**Pull request by hedcler**
Improve project structure:

- Change output path from `web/` to `public`
- Change default repository type to `vcs`
- Remove `github`, `bitbucket` and gitlab entries for repository types
- Add `.sublime-project` to gitignore
- Update README with new structure information
- Add Docker and Docker Compose installation info on README
- Add info on README to run project with Docker
- Update and improve `docker-compose.yml`
- Add contributors entry

### CODE REVIEW

**Comment by ramunasd** [comment]
Hi and thanks for efforts. What the point of renaming /web to /public? It is common practice or convention?
Next version 3.0 will be based on Symfony micro kernel and we will follow Symfony convention, so it's clear why /web was choosen.

**Comment by hedcler** [comment]
Hey @ramunasd !

Its just to know where is the public content. Different web servers use diferent paths. Nginx use `/var/www/html`, Apache use `public_html`, etc. Using `web/` or `public/` is indifferent because we need to configure root path on webserver. Or just mount it correctly inside a container.

**Comment by ramunasd** [comment]
Symfony best practices describes recommended and well known directory structure https://symfony.com/doc/current/best_practices/creating-the-project.html#structuring-the-application

cheers!

**Comment by hedcler** [comment]
Directory renamed. Let's follow the Symfony.

We'll continue to support PHP < 7.0 ? 

I think it's no needed because we are containerizing the app. I push PHP >= 7.1 to travis-ci can we do it?

**Comment by ramunasd** [comment]
Support for PHP <7.0 already dropped. Please take a look at upcoming version https://github.com/ludofleury/satisfy/releases/tag/3.0-rc1

**Comment by hedcler** [comment]
Ok. I'll close this PR and reopen following patterns on branch 3.x

**Pull request closed without merging**
