### PR TITLE
Fix edit function by indexing repositories with there id.

### PR DESCRIPTION
**Pull request by breaker92**
Cause the Manager class expected repositories indexed by id.

### CODE REVIEW

**Comment by breaker92** [comment]
Should solve #131

**Comment by ramunasd** [comment]
Thanks a lot! Tests are mandatory

**Comment by ramunasd** [comment]
Thanks @breaker92. In open source community it is common to submit PR or "patch" as one whole. I'd rather fix this on my own than cherry picking commits from different sources.
Also, test should reproduce issue. If you cannot edit repository due to wrong behaviour, then your test should imitate that action and test results :)

**Comment by ramunasd** [comment]
fixed in 3.2.4

**Pull request closed without merging**
