### PR TITLE
Use command console satisfy:rebuild instead of satis build

### PR DESCRIPTION
**Pull request by rabauss**
You have to use command ``satisfy:rebuild`` for parameter ``satis_filename``
Because satis build won't get the parameter...

### CODE REVIEW

**Comment by ramunasd** [comment]
Hi @rabauss thanks for contribution. This PR, well, isn't completely right. Indeed the command `satisfy:rebuild` sets correct params, but this can cause some side effects - build processcan be skipped if config file wasn't modified after last build.
IMHO we should set correct params in BuildRunner.

**Comment by ramunasd** [comment]
@rabauss I fixed this, from now `output-dir` is mandatory field.

**Comment by rabauss** [comment]
Okay, we tested the newest release:

The rebuild in the admin is using the config for output dir + satis_filename - perfect!
BUT if we use ``/bin/satis build`` the parameters are not used.

should the readme get an update, that you should run `bin/console satisfy:rebuild`?

**Comment by ramunasd** [comment]
@rabauss that's correct, satis itself does not know anything about custom paths. You must provide them manually or define alias.

**Pull request closed without merging**
