### PR TITLE
Persister corrupts json file when new config is smaller than previous

### PR DESCRIPTION
**Pull request by ramunasd**

### CODE REVIEW

**Comment by ludofleury** [comment]
Hey @ramunasd, you are pretty active on this project, would you be interested to become a maintainer ?

**Comment by ramunasd** [comment]
Hi @ludofleury , actually we are using this software as our internal repository. That's why we want fix all issue in it.

I can be maintainerif You like ")

**Comment by ludofleury** [comment]
You're added as a collaborator to this repo. 
Just be cautious when you tag a stable version & update packagist.
The project use semver (X.Y.Z).

Thanks & welcome on board !

**Comment by ludofleury** [comment]
@ramunasd I let you merge, tag & update packagist ?

**Comment by ramunasd** [comment]
@ludofleury Yes, you did. I just want to make it much better. I.e. write some unit tests and enable travis-ci. Some progress is here https://github.com/ludofleury/satisfy/compare/master...ramunasd:master

**Comment by ludofleury** [comment]
@ramunasd amazing. I never made time for this. Feel free to open a branch directly on the repo now.

**Pull request closed without merging**
