### PR TITLE
Updating to keep sync w/ composer/satis dev-master

### PR DESCRIPTION
**Pull request by oh4real**
1. Upgrading to 7.2 to "satisfy" composer/satis dev-master
2. adding zip and unzip so composer can install

### CODE REVIEW

**Comment by ramunasd** [comment]
Thanks a lot. This was planned for version 3.3 #100

**Comment by oh4real** [comment]
In the meantime, it's blocking `composer up` from within the container for our CI/CD pipeline. 

Since the travis tests pass, it'd be great if this update makes it soon so we don't have to fork for use in our CI/CD pipeline.

Please and thank you, but I understand if there are broader implications.

**Comment by ramunasd** [comment]
@oh4real can you please adjust `composer.json` and remove 7.1 build from travis config?

**Comment by oh4real** [comment]
Done

**Comment by ramunasd** [comment]
Please increase minimum required php versin at https://github.com/ludofleury/satisfy/blob/master/composer.json#L26

**Comment by oh4real** [comment]
Sorry. I've been in travis land, dealing with versions recently, so naturally i thought that was the only part I "read" of your request.

**Pull request merged**
