### PR TITLE
feat: Auto add repo upon Github/Gitea Webhook

### PR DESCRIPTION
**Pull request by gerdemann**

### CODE REVIEW

**Comment by gerdemann** [comment]
@ramunasd Now I have understood what you meant, I would also update this PR accordingly.

**Comment by gerdemann** [comment]
I have now updated the PR

**Comment by ramunasd** [comment]
please run `composer test` before submitting PR
looks like github CI does not work ATM

**Comment by gerdemann** [comment]
All tests are green now. ✅

**Pull request merged**
